### ISSUE TITLE
Bug in onPreferencesClickDisagreeToAll Event Handling

### ISSUE THREAD

**Issue by Tyrbok** [didomi/flutter#105]
There is an issue related to the event handling in part of the code where `onPreferencesClickDisagreeToAll` incorrectly triggers `onPreferencesClickAgreeToAll` instead of its own handler. This bug makes it impossible to accurately detect when a user has selected the DisagreeToAll option.

The issue seems to stem from a typo in the switch-case statement handling the event triggers. Here is the problematic part of the code:

https://github.com/didomi/flutter/blob/9e8b82484d429480249840a52d255a469df124f6/lib/events/events_handler.dart#L138

```dart
case "onPreferencesClickAgreeToAll":
    for (var listener in listeners) {
      listener.onPreferencesClickAgreeToAll();
    }
    break;

case "onPreferencesClickDisagreeToAll":
    for (var listener in listeners) {
      listener.onPreferencesClickAgreeToAll(); // This should call to disagree to all
    }
    break;
```

**Comment by nicolas-chaix-didomi** [comment]
Hello @Tyrbok ,
Thanks for your feed back, we will release a fix very soon

Kindly regards
