### ISSUE TITLE
Error : channel sent a message from native to Flutter on a non-platform thread

### ISSUE THREAD

**Issue by jeansebastienZ** [didomi/flutter#89]
Hello, 

Here an issue found wich seems to occur  on the first run once you click on accept && close  . 

`[VERBOSE-2:shell.cc(1004)] The 'didomi_sdk/events' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel. `

Flutter doctor :

**_[✓] Flutter (Channel stable, 3.13.8, on macOS 13.1 22C65 darwin-x64, locale fr-FR)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] Network resources_**

**Comment by jeansebastienZ** [comment]
For people looking for a fast solution I solved it by switching the eventSink.

From
```eventSink?(jsonString)```
To
```
DispatchQueue.main.async {
self.eventSink?(jsonString)
} 
```
Don't get time to test everything right now to be sure that there are no impact but i let it here if anyone deep it.

**Comment by pmerlet-at-didomi** [comment]
Hello @jeansebastienZ , thanks for your feedback. After a quick look, it seems your fix is the usual solution for recent Flutter versions, for example: https://github.com/firebase/flutterfire/pull/11650

**Comment by pmerlet-at-didomi** [comment]
👍  Sure, the fix should be in the next release.
